### ISSUE TITLE
Bakgrundsbild på startsidan

### ISSUE THREAD

**Issue by johansundstrom** [johansundstrom/powerteam#4]
Bilden är för hög och tar upp för mycket space

**Comment by jonperra** [comment]
Ok, ange pixelhöjd och jag laddar upp ny media

**Comment by johansundstrom** [comment]
Jag tänker att bäst är om huvudbudskapet kan få plats på en desktop webbsida. In den bör då rymmas
1) header med logo (ca 15%)
2) nav (ca 10%)
3) jumbotron med avsikt att passivt rotera mycket info snabbt. (ca 50%)
4) något som visar att det finns mer. (ca 25%)

**Comment by jonperra** [comment]
hm, får inte ihop förhållandena, ska jag ta bort mc-märkena? Kan ha dom på bakomliggande sidor under våra tjänster.

**Comment by johansundstrom** [comment]
Jag har croppat och mörkat ned bakgrundsbilden på startsidan. Vet inte om dekorbilden är viktig nog att inte manipuleras, det får du bestämma. Nu kräver inte inledande text och bild så mycket space som förrut.

**Comment by jonperra** [comment]
Definitivt annat men jag stör mig på den "Feta" headern, den tar alldeles för stor del i anspråk. Förhållandet bakgrund och loggan har jag satt till nästan 1,5:1 eller 106 och 70 pixlar, menyrade är i sammanhanget 33 pixlar. Går det inte att sätta en maxstorlek i pixlar eller riskeras den att bli beränsad
