### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by jonperra** [johansundstrom/powerteam#6]
Byta funktion till automatisk sidbyte.
Om möjligt implementera mp4-fil m ljud på slide 10 i carousel.html

**Comment by jonperra** [comment]
Vid kontrollmätning av exponeringstid per bil har jag fått fram manuella värden mellan 4.99 - 5.03 sekunder. Troligen är inställningen 5 sekunder, känns i kortaste laget.

**Comment by johansundstrom** [comment]
höjt till interval="3000" från interval="2000"
